services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-django_db}
      POSTGRES_USER: ${POSTGRES_USER:-django_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-django_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # по желанию, можно убрать

  web:
    build: .
    restart: unless-stopped
    command: >
      sh -c "python manage.py makemigrations crm && \
        python manage.py makemigrations manufacture && \
        python manage.py migrate && \
        python manage.py createsu &&
        python manage.py collectstatic --noinput && \
        python manage.py seed_demo_data && \
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./web:/app/web
      - static_volume:/app/web/staticfiles
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  static_volume:
